---
id: Cli_Modular
name: Cli_Modular
full: Modular command line interface library
description: >
  Command line interfaces can often be composed of different modules responsible
  for distinct actions. This package allows each such module to influence the
  overall command line interface. First and foremost each module can add its own
  option group with a specific title, description and a set of module specific
  options (see Horde_Argv_OptionGroup for further details). In addition
  Cli_Modular allows a module to modify the global usage string and add basic
  options valid for all modules.
list: dev
type: library
