---
id: Cli_Modular
name: Cli_Modular
full: Modular command line interface library
description: >-
  Command line interfaces can often be composed of different modules responsible
  for distinct actions. This package allows each such module to influence the
  overall command line interface. First and foremost each module can add its own
  option group with a specific title, description and a set of module specific
  options (see Horde_Argv_OptionGroup for further details). In addition
  Cli_Modular allows a module to modify the global usage string and add basic
  options valid for all modules.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Cli_Modular
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: false
    role: lead
version:
  release: 2.1.1
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Argv: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
